HW2 is completed
Mike0808/OtusGolang-home_work pull request #2
Opened 2022-06-14 10:36 UTC by Mike0808

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-18 10:55 UTC, agneum requested changes
Спасибо за вариант решения. 
Хорошая работа, однако есть предложения по улучшению и не хватает новых юнит-тестов, поэтому возвращаю на доработку

Итого: 5 баллов из 10

2022-06-18 10:55 UTC, agneum commented on hw02_unpack_string/unpack.go
> +package main
Зачем переименован пакет? В этом случае его не получится импортировать как зависимость

2022-06-18 10:55 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	fmt.Print(line)
Новые сценарии и все проверки лучше добавить в тесты

2022-06-18 10:55 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	var sb strings.Builder
Оптимальнее сначала проверить длину строки и первый символ, а затем инициализировать strings.Builder

2022-06-18 10:55 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			if runeSlice[i+1] == 48 || runeSlice[i] == 48 {
Не очевидно, что происходит сравнение с 0. Рекомендую хотя бы оставить комментарий

2022-06-18 10:55 UTC, agneum commented on hw02_unpack_string/unpack_test.go
> +package main
Не хватает новый юнит-тестов

2022-06-19 10:07 UTC, Mike0808 commented
@agneum 
Замечания устранил, можно проверять

2022-06-20 02:47 UTC, agneum approved these changes
Спасибо за правки. Хорошая работа
Итого: 10 баллов из 10

2022-06-20 03:54 UTC, merged