HW3 for review
Mike0808/OtusGolang-home_work pull request #3
Opened 2022-06-21 04:33 UTC by Mike0808

## Домашнее задание №3 «Частотный анализ»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-06-21 15:31 UTC, agneum requested changes
Спасибо за выполненное задание.
Хорошая работа, однако есть комментарии и предложения по улучшению, а так же не хватает новых юнит-тестов

Итого: 5 баллов из 10

2022-06-21 15:31 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	t := regexp.MustCompile(`\s+`)
Рекомендую обратить внимание на [частые ошибки](https://github.com/pabateman/otus-golang-hw/tree/hw03_frequency_analysis/hw03_frequency_analysis#%D1%87%D0%B0%D1%81%D1%82%D1%8B%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B8) при выполнении задания

2022-06-21 15:31 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	words := []Words{}
Предлагаю при создании слайса указать capacity, чтобы уменьшить количество аллокаций при добавлении элементов

2022-06-21 15:31 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	sort.SliceStable(words, func(i, j int) bool { return words[i].Count > words[j].Count })
Можно отсортировать за один вызов функции - просто условия внутри компаратора будут немного сложнее

2022-06-21 15:31 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		if w.Count > 1 {
Как такое может произойти, что Count меньше 1?

2022-06-22 04:43 UTC, Mike0808 commented
@agneum 
Добрый день. Спасибо за ревью. Исправил замечания. Добавил задание со *

2022-06-22 14:46 UTC, agneum commented
> @agneum Добрый день. Спасибо за ревью. Исправил замечания. Добавил задание со *

Спасибо за правки, однако новых юнит-тестов так и не добавилось
Итого: 6 баллов из 10

2022-06-23 04:25 UTC, Mike0808 commented
@agneum 
Доброго. Добавил тесты, нашел ошибку. Спасибо.

2022-06-23 10:33 UTC, agneum approved these changes
Спасибо за правки и тесты.
Принято: 10/10

2022-06-29 03:37 UTC, merged