HW4 for review - 1
Mike0808/OtusGolang-home_work pull request #4
Opened 2022-07-01 06:58 UTC by Mike0808

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-07-10 17:21 UTC, farir1408 requested changes

2022-07-10 17:21 UTC, farir1408 commented on hw04_lru_cache/cache.go
> +	c.queue.(*List).list = nil
Почему не взять и просто создать новый лист?

2022-07-10 17:21 UTC, farir1408 commented on hw04_lru_cache/go.mod
>  require (
Необходимо поправить название модуля.

2022-07-10 17:21 UTC, farir1408 commented on hw04_lru_cache/list.go
> +func (l *List) Back() *ListItem {
Кажется, у вас реализован кольцевой двусвязный список. Но это не обычный двусвязный список. В таком случае нам лучше хранить head и tail элементы.

2022-07-10 17:21 UTC, farir1408 commented on hw04_lru_cache/list.go
> +	list *List
Зачем нам в листе хранить указатель на самих же себя?

2022-07-10 17:21 UTC, farir1408 commented
Здравствуйте. Необходимо предусмотреть 2 указателя у списка. У первого элемента есть next, но prev=nil. У последнего элемента есть prev, но next=nil.

2022-07-12 10:38 UTC, Mike0808 commented
@farir1408  Добрый день. Поправил согласно замечаниям. Спасибо

2022-07-14 12:02 UTC, farir1408 approved these changes

2022-07-14 12:02 UTC, farir1408 commented
Здравствуйте!

Спасибо за выполнение домашнего задания.
Хорошая работа, принято 10/10.

2022-07-19 17:13 UTC, merged